## This configuration was generated by terraform-provider-oci

resource oci_core_nat_gateway export_NAT-gateway-VCN-01 {
  block_traffic  = "false"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:31.292Z"
  }
  display_name = "NAT gateway-VCN-01"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  #public_ip_id = "ocid1.publicip.oc1.iad.aaaaaaaatanmdsplwxirnaatnj6cn5wgslps6jdcbaedmfuu54b5x42dt4ua"
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_internet_gateway export_Internet-gateway-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:31.141Z"
  }
  display_name = "Internet gateway-VCN-01"
  enabled      = "true"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  #route_table_id = <<Optional value not found in discovery>>
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_default_dhcp_options export_Default-DHCP-Options-for-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:29.994Z"
  }
  display_name     = "Default DHCP Options for VCN-01"
  domain_name_type = "CUSTOM_DOMAIN"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  manage_default_resource_id = "ocid1.dhcpoptions.oc1.iad.aaaaaaaalipmrn2wz4ppft5kv3lnajdphtyif66vitthxhuyko62xpgsie6q"
  options {
    custom_dns_servers = [
    ]
    #search_domain_names = <<Optional value not found in discovery>>
    server_type = "VcnLocalPlusInternet"
    type        = "DomainNameServer"
  }
  options {
    #custom_dns_servers = <<Optional value not found in discovery>>
    search_domain_names = [
      "vcn01.oraclevcn.com",
    ]
    #server_type = <<Optional value not found in discovery>>
    type = "SearchDomain"
  }
}

resource oci_core_vcn export_VCN-01 {
  #byoipv6cidr_details = <<Optional value not found in discovery>>
  #cidr_block = <<Optional value not found in discovery>>
  cidr_blocks = [
    "10.0.0.0/16",
  ]
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:29.994Z"
  }
  display_name = "VCN-01"
  dns_label    = "vcn01"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  ipv6private_cidr_blocks = [
  ]
  #is_ipv6enabled = <<Optional value not found in discovery>>
  #is_oracle_gua_allocation_enabled = <<Optional value not found in discovery>>
}

resource oci_core_subnet export_private-subnet-VCN-01 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.1.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:31.136Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-VCN-01.id
  display_name    = "private subnet-VCN-01"
  dns_label       = "sub02241549271"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "true"
  prohibit_public_ip_on_vnic = "true"
  route_table_id             = oci_core_route_table.export_route-table-for-private-subnet-VCN-01.id
  security_list_ids = [
    oci_core_security_list.export_security-list-for-private-subnet-VCN-01.id,
  ]
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_subnet export_public-subnet-VCN-01 {
  #availability_domain = <<Optional value not found in discovery>>
  cidr_block     = "10.0.0.0/24"
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:31.123Z"
  }
  dhcp_options_id = oci_core_default_dhcp_options.export_Default-DHCP-Options-for-VCN-01.id
  display_name    = "public subnet-VCN-01"
  dns_label       = "sub02241549270"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  #ipv6cidr_block = <<Optional value not found in discovery>>
  ipv6cidr_blocks = [
  ]
  prohibit_internet_ingress  = "false"
  prohibit_public_ip_on_vnic = "false"
  route_table_id             = oci_core_vcn.export_VCN-01.default_route_table_id
  security_list_ids = [
    oci_core_vcn.export_VCN-01.default_security_list_id,
  ]
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_security_list export_security-list-for-private-subnet-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:31.605Z"
  }
  display_name = "security list for private subnet-VCN-01"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_default_security_list export_Default-Security-List-for-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:29.994Z"
  }
  display_name = "Default Security List for VCN-01"
  egress_security_rules {
    #description = <<Optional value not found in discovery>>
    destination      = "0.0.0.0/0"
    destination_type = "CIDR_BLOCK"
    #icmp_options = <<Optional value not found in discovery>>
    protocol  = "all"
    stateless = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    #icmp_options = <<Optional value not found in discovery>>
    protocol    = "6"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    tcp_options {
      max = "22"
      min = "22"
      #source_port_range = <<Optional value not found in discovery>>
    }
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "4"
      type = "3"
    }
    protocol    = "1"
    source      = "0.0.0.0/0"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  ingress_security_rules {
    #description = <<Optional value not found in discovery>>
    icmp_options {
      code = "-1"
      type = "3"
    }
    protocol    = "1"
    source      = "10.0.0.0/16"
    source_type = "CIDR_BLOCK"
    stateless   = "false"
    #tcp_options = <<Optional value not found in discovery>>
    #udp_options = <<Optional value not found in discovery>>
  }
  manage_default_resource_id = oci_core_vcn.export_VCN-01.default_security_list_id
}

resource oci_core_route_table export_route-table-for-private-subnet-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:31.186Z"
  }
  display_name = "route table for private subnet-VCN-01"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_nat_gateway.export_NAT-gateway-VCN-01.id
    #route_type = <<Optional value not found in discovery>>
  }
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "all-iad-services-in-oracle-services-network"
    destination_type  = "SERVICE_CIDR_BLOCK"
    network_entity_id = oci_core_service_gateway.export_Service-gateway-VCN-01.id
    #route_type = <<Optional value not found in discovery>>
  }
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_default_route_table export_default-route-table-for-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:29.994Z"
  }
  display_name = "default route table for VCN-01"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  manage_default_resource_id = oci_core_vcn.export_VCN-01.default_route_table_id
  route_rules {
    #description = <<Optional value not found in discovery>>
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
    network_entity_id = oci_core_internet_gateway.export_Internet-gateway-VCN-01.id
    #route_type = <<Optional value not found in discovery>>
  }
}

resource oci_core_service_gateway export_Service-gateway-VCN-01 {
  compartment_id = var.compartment_ocid
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:49:31.130Z"
  }
  display_name = "Service gateway-VCN-01"
  freeform_tags = {
    "VCN" = "VCN-2024-02-24T15:48:39"
  }
  #route_table_id = <<Optional value not found in discovery>>
  services {
    service_id = "ocid1.service.oc1.iad.aaaaaaaam4zfmy2rjue6fmglumm3czgisxzrnvrwqeodtztg7hwa272mlfna"
  }
  vcn_id = oci_core_vcn.export_VCN-01.id
}

resource oci_core_instance export_VM-01 {
  agent_config {
    are_all_plugins_disabled = "false"
    is_management_disabled   = "false"
    is_monitoring_disabled   = "false"
    plugins_config {
      desired_state = "DISABLED"
      name          = "Vulnerability Scanning"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Oracle Java Management Service"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "OS Management Service Agent"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Management Agent"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Custom Logs Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Compute RDMA GPU Monitoring"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Run Command"
    }
    plugins_config {
      desired_state = "ENABLED"
      name          = "Compute Instance Monitoring"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Compute HPC RDMA Auto-Configuration"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Compute HPC RDMA Authentication"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Block Volume Management"
    }
    plugins_config {
      desired_state = "DISABLED"
      name          = "Bastion"
    }
  }
  #async = <<Optional value not found in discovery>>
  availability_config {
    #is_live_migration_preferred = <<Optional value not found in discovery>>
    recovery_action = "RESTORE_INSTANCE"
  }
  availability_domain = var.availability_domain--ljKK-US-ASHBURN-AD-1
  #capacity_reservation_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  #compute_cluster_id = <<Optional value not found in discovery>>
  create_vnic_details {
    #assign_ipv6ip = <<Optional value not found in discovery>>
    #assign_private_dns_record = <<Optional value not found in discovery>>
    assign_public_ip = "true"
    defined_tags = {
      "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
      "Oracle-Tags.CreatedOn" = "2024-02-24T15:59:03.298Z"
    }
    display_name = "instance-20240224-1750"
    freeform_tags = {
    }
    hostname_label = "instance-20240224-1750"
    #ipv6address_ipv6subnet_cidr_pair_details = <<Optional value not found in discovery>>
    nsg_ids = [
    ]
    #private_ip             = "10.0.0.108"
    skip_source_dest_check = "false"
    subnet_id              = oci_core_subnet.export_public-subnet-VCN-01.id
    #vlan_id = <<Optional value not found in discovery>>
  }
  #dedicated_vm_host_id = <<Optional value not found in discovery>>
  defined_tags = {
    "Oracle-Tags.CreatedBy" = "default/99069114-lab.user01"
    "Oracle-Tags.CreatedOn" = "2024-02-24T15:59:03.134Z"
  }
  display_name = "VM-01"
  extended_metadata = {
  }
  fault_domain = var.fault_domain--FAULT-DOMAIN-1
  freeform_tags = {
  }
  #instance_configuration_id = <<Optional value not found in discovery>>
  instance_options {
    are_legacy_imds_endpoints_disabled = "false"
  }
  #ipxe_script = <<Optional value not found in discovery>>
  #is_pv_encryption_in_transit_enabled = <<Optional value not found in discovery>>
  #launch_options {
    #boot_volume_type                    = "PARAVIRTUALIZED"
    #firmware                            = "UEFI_64"
    #is_consistent_volume_naming_enabled = "true"
    #is_pv_encryption_in_transit_enabled = "true"
    #network_type                        = "PARAVIRTUALIZED"
    #remote_data_volume_type             = "PARAVIRTUALIZED"
  #}
  metadata = {
    "ssh_authorized_keys" = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCj+krouTwVDbTeIv/IntmeMfxrl2ZlvMGQS/6evsKJ1Y6nqv8uTn99ObY9/Eg1u+2IhiuCKecH47HjDa4MAWDKvjglGyL2sSkbiH1D3h0C/ubm7oVpN42Q02tqbp9lLzmzVAPdUJbg7ycH7My20Ko79B4PU/AfEfq2icyExyAbVjddjp7HwTNYUkVrHJo+sYGl3TZPHpuPUpBYnRbilFab6FOLE6uFTZpIOCdc+QCgBIKXI7Z8tJQHsawdTrtHWF6eNVXznbnQgH7uS7hsKAWdW8IaysS7jAXtpy0LxWNXWAKpWRjwibJvUZb0NoV8jIVdtMHEwPVmMGc8DLfazifjhR7vs74o98LrHlcPRpF/w1RwBPZt1aWhUpXMuIIYurFiFeKhOg+VsSRxvL2jfQyiWgnbtlK/ZTHJAlkb9ounvu2ykfJySEkKx0y8W4zR4r7V282a2gKqUhVV+sAYWThHo8LgKcKZIzGPZYQkJwVUMKVljWx6pPFZ/csZ0vnn8csEOwqqU+2xXs0D8rQ1mo1rP79UPxanTBSkCr9FN7ORyqseuXmo0r7+n4mxV0fdYv1qeQWfkTR2nM+TNL4HIyF0GH/yzq1yzNIA8KgXhGg8YOQ9cG7ZgKVLFBEx/0wkRuGpvAq8UYClSPjyQtGexljIlUJEbJjZii0nvPYF38m4rw== x_99069114@d132f9e1f9b7"
  }
  #preserve_boot_volume = <<Optional value not found in discovery>>
  shape = "VM.Standard.A1.Flex"
  shape_config {
    #baseline_ocpu_utilization = ""
    memory_in_gbs             = "6"
    #nvmes                     = "0"
    ocpus                     = "1"
    vcpus                     = "1"
  }
  source_details {
    #boot_volume_size_in_gbs = <<Optional value not found in discovery>>
    boot_volume_vpus_per_gb = "10"
    #instance_source_image_filter_details = <<Optional value not found in discovery>>
    #kms_key_id = <<Optional value not found in discovery>>
    source_id   = var.oci_core_instance--source_details-source_id--export_VM-01
    source_type = "image"
  }
  state = "RUNNING"
  #update_operation_constraint = <<Optional value not found in discovery>>
}

